version: '3'

services:
  app1:
    build: .
    ports:
      - "3001:2727"
    networks:
      - app-network

  app2:
    build: .
    ports:
      - "3002:2727"
    networks:
      - app-network
  
  nginx:
    image: nginx
    ports:
      - 7777:7777
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 

networks:
  app-network:
